export const IPC_EVENTS = {
  title_documents: 'title_documents',
  menu_viewer: 'menu_viewer',
  document_content_path: 'document_content_path',
  document_tabs: 'document_tabs',
  search_suggestions: 'search_suggestions',
  search_text: 'search_text',
  search_content: 'search_content',
  subject_document: 'subject_document',
  subject_items: 'subject_items',
  subject_items_delete: 'subject_items_delete',
  subject_document_delete: 'subject_document_delete',
  subject_items_store: 'subject_items_store',
  open_modal_document_from_main: 'open_modal_document_from_main',
  custom_documents: 'custom_documents',
  custom_documents_delete: 'custom_documents_delete',
  custom_documents_store: 'custom_documents_store',
};
